root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main ."
  bin = "./tmp/main"
  # delay = 100
  exclude_dir = ["assets", "tmp", "vendor", "dist"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  exclude_regex = ["_templ\\.go","_test\\.go"]
  env = [
	"DEV=true"
]

[screen]
  clear_on_rebuild = true
